### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#108]
## Description

The packages in the project need to be updated to the latest. However, there are interdependencies between the packages (e.g. currently configured TypeScript plugin for ESLint doesn't support TypeScript versions above 4.5.0).

## Objectives

- [x] Update Dependencies (By default versions will be preceded by `^`. But, you might have to hard configure versions (without the `^`). Watch out for such cases.)
- [x] Check that all `yarn` scripts defined in `package.json` are running.

**Comment by DipayanP007** [comment]
Hey @meganindya are there any specific versions to which updation needs to be done?

**Comment by ColabAkshat** [comment]
I am on it, may take time.
