### ISSUE TITLE
Specification: Add validation in functions

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#112]
## Description

Add validation to the functions in [`src/syntax/specification/specification.ts`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/develop/src/syntax/specification/specification.ts). Add tests for the added validations in [`src/syntax/specification/specification.spec.ts`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/develop/src/syntax/specification/specification.spec.ts).

## Objectives

- [ ] `registerElementSpecificationEntry`: return `false` if element name already exists else `true`
- [ ] `registerElementSpecificationEntry`: add tests for the validation
- [ ] `registerElementSpecificationEntries`: add only entries for elements that don't exist; return a boolean array (see previous)
- [ ] `registerElementSpecificationEntries`: add tests for the validation
- [ ] `removeElementSpecificationEntry`: return `true` is successfully removed else `false`
- [ ] `removeElementSpecificationEntry`: add tests for the validation
- [ ] `removeElementSpecificationEntries`: return a boolean array (see previous)
- [ ] `removeElementSpecificationEntries`: add tests for the validation

Make changes to the return type definitions (and add TSDoc comment for `@returns`). Please keep commits separate.

**Comment by ColabAkshat** [comment]
I want to work on this issue, assign me!

**Comment by ColabAkshat** [comment]
Created a pull request, you can review it.
