### ISSUE TITLE
Specification: Add snapshot function

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#113]
## Description

Add a function to return the snapshot of the element specification in [`src/syntax/specification/specification.ts`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/develop/src/syntax/specification/specification.ts). Add tests for the added function in [`src/syntax/specification/specification.spec.ts`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/develop/src/syntax/specification/specification.spec.ts).

The signature is

```typescript
/**
 * Returns ...
 * @returns - ...
 */
export function generateSnapshot(): {
  [key: string]: {
    ...
    // all properties of IElementSpecification except prototype (see @types/specification.d.ts)
    ...
    prototypeName: string // name of the class (.name)
  }
}
```

## Objectives

- [ ] add function `generateSnapshot()` (and TSDoc documentation)
- [ ] add tests for the added function

Please keep commits separate.

**Comment by ColabAkshat** [comment]
I want to work on this issue. Assign it me.

**Comment by ColabAkshat** [comment]
What is the return type of this function? Is it ITreeSnapshot?

**Comment by meganindya** [comment]
```ts
interface IElementSpecificationSnapshot extends Omit<IElementSpecification, 'prototype'> {
    prototypeName: string;
}
```
