### ISSUE TITLE
Port musicutils prototype code from Python to TypeScript

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#18]
Some prototype structures have been implemented in _Python_ for music utilities. They are present on the `musicutils` branch in the [`src/.prototype/musicutils`](https://github.com/sugarlabs/musicblocks-lib/tree/musicutils/src/.prototype/musicutils) directory.

Port these files and the unit test file to _TypeScript 4_. The unit test, as ported, should be evaluated in the configured `ts-jest` with `npm test ...`. The files have interdependencies, so follow the order:

- [x] [`scale.py`](https://github.com/sugarlabs/musicblocks-lib/blob/musicutils/src/.prototype/musicutils/scale.py) #24
- [x] [`musicutils.py`](https://github.com/sugarlabs/musicblocks-lib/blob/musicutils/src/.prototype/musicutils/musicutils.py) #28
- [x] [`keysignature.py`](https://github.com/sugarlabs/musicblocks-lib/blob/musicutils/src/.prototype/musicutils/keysignature.py) #22
- [x] [`temperament.py`](https://github.com/sugarlabs/musicblocks-lib/blob/musicutils/src/.prototype/musicutils/temperament.py) #23
- [x] [`currentpitch.py`](https://github.com/sugarlabs/musicblocks-lib/blob/musicutils/src/.prototype/musicutils/currentpitch.py) #26

If possible, split the `utils_unittest.py` for individual files, going one at a time according to the order above.

Sticking to _TypeScript_ conventions, use _PascalCase_ for filenames, _CAPITALCASE_ for constants, _camelCase_ for identifiers. Linting has been strictly configured. A `super-linter` is configured to lint check the files on a pull request. In fact, the _TypeScript_ watcher or build will throw errors/warnings if there are linting problems. This has been done to maintain code quality.

For now, create a new directory named _ts_ in `src/.prototype/musicutils`, and put your new files there. This need not be done has one large PR. But, please follow the file separation at a time. Create a draft PR to start any discussions if required. Should have the test code (pertaining to the corresponding file/s) before each PR is reviewed.

**Comment by b18050** [comment]
@meganindya I am unable to locate .prototype locally, but I see it's on my fork.
When I am in my develop branch,
I am trying to fetch `musicutils` branch locally using command
`git fetch origin musicutils:localbranch `.
`git checkout localbranch`  .
But no files get added in localbranch.

**Comment by ksraj123** [comment]
Working on `musticutils.py` . Commenting to avoid conflicts with others. Thanks

**Comment by meganindya** [comment]
Please hold onto your PR temporarily.

Since the current code is in Python, the paraphernalia is according to Python conventions. This port needs to be in accordance with JavaScript/TypeScript conventions.

#20 isn't what I was expecting. I'll port `scale.py` and its unit tests, and thereafter please follow that style for the rest. Need to go line by line for review. So please make one PR for each of the remaining 4 files (and corresponding unit tests).

**Comment by daksh4469** [comment]
I want to work on `temperament.py` and `currentpitch.py`. Once @meganindya ports `scale.py`, I will start working on these files with the style that he has followed. Commenting to avoid conflicts.
Thanks.

**Comment by meganindya** [comment]
Not a race :p 

Please follow these: https://github.com/sugarlabs/musicblocks-lib#code-quality-notes

**Comment by meganindya** [comment]
I've ported `scale.py` as a sample. Created a directory `ts` in `src/.prototype/musicutils/` which now contains `scale.ts` and `scale.test.ts`. A subdirectory of `ts` named `@types` contains `scale.d.ts`.

Please observe #18. And, follow the code quality notes for the remainder. Target your PR to `musicutils` branch and not `develop` (`develop` is the default branch; `musicutils` on completion will be merged into `develop`).

**Comment by daksh4469** [comment]
Do we need to follow a specific convention to describe unit tests or any applicable description is fine? @meganindya

**Comment by meganindya** [comment]
Please improvise as required. I merely showed a sample. My test suite has a `class Scale` as a test header, followed by `Validate scale generation` which is like a section, which in turn contains the unit tests relevant to the section.

**Comment by daksh4469** [comment]
In #27, I have added sections in the test according to the methods of the Musicutils class so as to group all tests concerning a single method under a single section.

**Comment by meganindya** [comment]
I perhaps mistakenly overlapped some work. Hereafter, let's keep it pronounced.

Since, `scale.py` and `musicutils.py` have been ported, you can proceed with `keysignature.py` and `temperament.py` independently of each other.

Please proceed on an assign basis.

`currentpitch.py` is dependent on the said two, so that will have to wait.

**Comment by ksraj123** [comment]
`temperament.py` completely ported in #23 - some finishing touches left, after which a PR to musicutils branch will be opened
part of `keySignature.py` ported in #22 - remaining part almost done, currently actively being worked upon in local
`currentpitch.py` - ported in #26 - test cases will be added after the other two files are completed
cc @meganindya @daksh4469

**Comment by meganindya** [comment]
All files ported.
