### ISSUE TITLE
Add TypeScript targeting README for musicutils

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#30]
On branch [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils), the music utilities are described in [`src/.prototype/musicutils/README.md`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/musicutils/src/.prototype/musicutils/README.md). However, that targets the prototype code written in _Python_.

As the _Python_ files are ported to _TypeScript_, the `README` needs to be updated accordingly. The file has 6 sections; update them based on the current `README` and the new `.ts` files in the [`src/.prototype/musicutils/ts/`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils/src/.prototype/musicutils/ts) directory.

The sections are:

- [x] `Current Pitch` #48
- [x] `Temperament` #31
- [x] `Key Signature` #54
- [x] `Scale` #50
- [x] `Music Utils` #49
- [x] `Example` #53

Create a new file `README.md` inside the `ts` directory.

Depends on #18.

**Comment by meganindya** [comment]
#18 is complete. The PRs for this were supposed to wait for that. Anyway, it is open now.

Most PRs aren't exactly in line. Use #48 as a template.

**Comment by meganindya** [comment]
It isn't exactly as is from the Python code. Please improvise and improve the docs as you go. Use the signatures in the `.ts` files exactly.

**Comment by ksraj123** [comment]
The `keysignature` part should be done after #46  and #47 are done.
