### ISSUE TITLE
Add unary and binary operators to primitive element classes

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#6]
File path: [`src/.prototype/syntaxElements/primitiveElements.ts`](https://github.com/sugarlabs/musicblocks-lib/blob/develop/src/.prototype/syntaxElements/primitiveElements.ts)
Unit-test file path: [`src/.prototype/syntaxElements/primitiveElements.test.ts`](https://github.com/sugarlabs/musicblocks-lib/blob/develop/src/.prototype/syntaxElements/primitiveElements.test.ts)

Identify (please list down in a comment) required unary and binary operators for the primitive types:
- [x] `TInt`
- [x] `TFloat`
- [ ] `TChar`
- [x] `TString`
- [ ] `TBoolean`

Implement the identified operators as object (non-static) and class (static) methods:
- [x] `TInt` (operands of type `TInt`)
  - [x] `add: void` (unary)
  - [x] `add: TInt` (binary)
  - [x] `subtract: void` (unary)
  - [x] `subtract: TInt` (binary)
  - [x] `multiply: void` (unary)
  - [x] `multiply: TInt` (binary)
  - [x] `divide: void` (unary)
  - [x] `divide: TInt` (binary)
  - [x] `mod: void` (unary)
  - [x] `mod: TInt` (binary)
  - [x] `greaterThan: TBoolean` (binary)
  - [x] `lessThan: TBoolean` (binary)
  - [x] `equals: TBoolean` (binary)
  - [x] `increment: void` (unary)
  - [x] `decrement: void` (unary)
- [x] `TFloat` (operands of type `TInt | TFloat`)
  - [x] `add: void` (unary)
  - [x] `add: TFloat` (binary)
  - [x] `subtract: void` (unary)
  - [x] `subtract: TFloat` (binary)
  - [x] `multiply: void` (unary)
  - [x] `multiply: TFloat` (binary)
  - [x] `divide: void` (unary)
  - [x] `divide: TFloat` (binary)
  - [x] `mod: void` (unary)
  - [x] `mod: TFloat` (binary)
  - [x] `greaterThan: TBoolean` (binary)
  - [x] `lessThan: TBoolean` (binary)
  - [x] `equals: TBoolean` (binary)
  - [x] `increment: void` (unary)
  - [x] `decrement: void` (unary)
- [ ] `TChar`
- [ ] `TString`
  - [ ] `length: () => TInt`
  - [ ] `charAt: (index: TInt) => TChar` (throw index out of bounds error)
  - [ ] `indexOf: (substring: TChar | TString) => TInt`
  - [ ] `substring: (startIndex: TInt, length?: TInt) => TChar` (throw index out of bounds error, invalid length only if < 0)
  - [ ] `equals: (operand: TChar | TString) => TBoolean`
  - [ ] `static equals: (operand_1: TChar | TString, operand_2: TChar | TString) => TBoolean`
  - [ ] `compareTo: (operand: TChar | TString) => TInt`
  - [ ] `static compare: (operand_1: TChar | TString, operand_2: TChar | TString) => TInt`
- [ ] `TBoolean`

Write unit tests for the implemented operators:
- [x] `TInt` (operands of type `TInt`)
  - [x] `add: void` (unary)
  - [x] `add: TInt` (binary)
  - [x] `subtract: void` (unary)
  - [x] `subtract: TInt` (binary)
  - [x] `multiply: void` (unary)
  - [x] `multiply: TInt` (binary)
  - [x] `divide: void` (unary)
  - [x] `divide: TInt` (binary)
  - [x] `mod: void` (unary)
  - [x] `mod: TInt` (binary)
  - [x] `greaterThan: TBoolean` (binary)
  - [x] `lessThan: TBoolean` (binary)
  - [x] `equals: TBoolean` (binary)
  - [x] `increment: void` (unary)
  - [x] `decrement: void` (unary)
- [x] `TFloat` (operands of type `TInt | TFloat`)
  - [x] `add: void` (unary)
  - [x] `add: TFloat` (binary)
  - [x] `subtract: void` (unary)
  - [x] `subtract: TFloat` (binary)
  - [x] `multiply: void` (unary)
  - [x] `multiply: TFloat` (binary)
  - [x] `divide: void` (unary)
  - [x] `divide: TFloat` (binary)
  - [x] `mod: void` (unary)
  - [x] `mod: TFloat` (binary)
  - [x] `greaterThan: TBoolean` (binary)
  - [x] `lessThan: TBoolean` (binary)
  - [x] `equals: TBoolean` (binary)
  - [x] `increment: void` (unary)
  - [x] `decrement: void` (unary)
- [ ] `TChar`
- [ ] `TString`
  - [ ] `length: () => TInt`
  - [ ] `charAt: (index: TInt) => TChar` (throw index out of bounds error)
  - [ ] `indexOf: (substring: TChar | TString) => TInt`
  - [ ] `substring: (startIndex: TInt, length?: TInt) => TChar` (throw index out of bounds error, invalid length only if < 0)
  - [ ] `equals: (operand: TChar | TString) => TBoolean`
  - [ ] `static equals: (operand_1: TChar | TString, operand_2: TChar | TString) => TBoolean`
  - [ ] `compareTo: (operand: TChar | TString) => TInt`
  - [ ] `static compare: (operand_1: TChar | TString, operand_2: TChar | TString) => TInt`
- [ ] `TBoolean`

Some have already been added. Please add the rest.

**Comment by sj00coder** [comment]
@meganindya I want to work on it.From where should I start?

**Comment by ricknjacky** [comment]
@meganindya as is, I presume all operations and tests for `TInt `and `TFloat `have been added. 
Could you please, shed some light on operations we're looking to add for: `TString`, `TChar`, `TBoolean`. 

If any remain, I'll add them asap.

**Comment by meganindya** [comment]
Suggest whatever you think works.

**Comment by ricknjacky** [comment]
> Suggest whatever you think works.

For `TString`:- 

- unary plus operator (using it as a prefix of variable that holds the number in string format, converts that number to number)
- 
- The + operator can also be used to add (concatenate) strings.
- 
- The += assignment operator can also be used to add (concatenate) strings
- 
- The `.length` operator, I presume will be the most used one. 
- 
- Similarly, `.indexOf`, `.substring` might as well be a good addition. 
- 
- Comparison operators idts we will use them when it comes to strings, but might as well be a good addition. Namely, `<`, `>`, `==`, `===`

Also, idts there are any more operations we can add to `TBoolean` that we would use sometime in the near future.

Should I go ahead with adding all of the above, or some of them, maybe some more to the list? please share your thoughts on this.

**Comment by meganindya** [comment]
(`TString`) Go with (all non-static if not mentioned):
- [ ] `length: () => TInt`
- [ ] `charAt: (index: TInt) => TChar` (throw index out of bounds error)
- [ ] `indexOf: (substring: TChar | TString) => TInt`
- [ ] `substring: (startIndex: TInt, length?: TInt) => TChar` (throw index out of bounds error, invalid length only if < 0)
- [ ] `equals: (operand: TChar | TString) => TBoolean`
- [ ] `static equals: (operand_1: TChar | TString, operand_2: TChar | TString) => TBoolean`
- [ ] `compareTo: (operand: TChar | TString) => TInt`
- [ ] `static compare: (operand_1: TChar | TString, operand_2: TChar | TString) => TInt`

**Comment by ricknjacky** [comment]
![Screenshot (557)](https://user-images.githubusercontent.com/50985033/107115925-f84ace80-6895-11eb-878c-190c84bb20d5.png)

This is what we want right?

**Comment by meganindya** [comment]
6 are non-static, 2 are static. non-static ones operate on the current object itself, static ones operate on the arguments. Also `camelCase` please. Pls use meaningful error messages. This design uses a lot of intentional error messages, we gotta know exactly where and why they originate.

**Comment by meganindya** [comment]
> > * [ ]   `length: () => TInt`
> > * [ ]   `charAt: (index: TInt) => TChar` (throw index out of bounds error)
> > * [ ]   `indexOf: (substring: TChar | TString) => TInt`
> > * [ ]   `substring: (startIndex: TInt, length?: TInt) => TChar` (throw index out of bounds error, invalid length only if < 0)
> > * [ ]   `equals: (operand: TChar | TString) => TBoolean`
> > * [ ]   `static equals: (operand_1: TChar | TString, operand_2: TChar | TString) => TBoolean`
> > * [ ]   `compareTo: (operand: TChar | TString) => TInt`
> > * [ ]   `static compare: (operand_1: TChar | TString, operand_2: TChar | TString) => TInt`

Pls use these signatures as is

**Comment by ricknjacky** [comment]
Did the changes:-
```
    length(){
        return new TInt(this._value.length);
    }

    charAt(operand_1: TInt){
        if (this._value.length > 0) {
            return new TString(this._value.charAt(operand_1.value));
        }
        else {
            throw new Error("length of string less than 0 --> outOfBoundException ");
        }
    }

    indexOf(searchTerm: TString | TChar, operand_1: TString | TChar){
        return new TInt(operand_1.value.indexOf(searchTerm.value));
    }

}
```

**Comment by meganindya** [comment]
use the same signatures ... these are different

`charAt`: out of bounds is for the index ... index must lie in [0, length - 1]

**Comment by ricknjacky** [comment]
> use the same signatures ... these are different
> 
> `charAt`: out of bounds is for the index ... index must lie in [0, length - 1]

I am kind of stuck here, do I just add the methods above, as is? 
If not, can you please, write a prototype version for one of the methods listed above. So that I get an idea of what is expected.

**Comment by meganindya** [comment]
```typescript
length(): TInt {
    return new TInt(this.value.length);
}

charAt(index: TInt): TChar {
    const thisStr = this.value;
    const indxInt = index.value;
    if (indxInt < 0 || indxInt >= thisStr.length) {
        throw Error(`String index "${indxInt}" out of bounds`);
    }
    return new TChar(thisStr.charAt(indxInt));
}
```
